spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

# AWS 사용할 것이므로
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa

  h2:
    console:
      enabled: true

#  profiles:
#    include: secret
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 985335857346-34pqastkrn7ubbaq4l60hv3bm20nc0hj.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: chj7785@gmail.com
  secret_key: study-springboot